import { TemplateConfig } from "./schema";

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 1,
    code: "temp_1",
    name: "Hoàng Kim Xanh",
    style: "Hoàng gia",
    preview:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=800&fit=crop&auto=format",
    themeClass: "theme-pink",
    tier: "basic",
    price: 460000,
    accentColor: "#db2777",
    envelopeKey: "minimal",
    timelineKey: "simple",
    galleryKey: "grid",
    schema: {
      basicInfo: {
        hasParentsInfo: true,
        hasRankInfo: true,
        hasAddressInfo: true,
      },
      cover: { hasBackgroundVideo: false, hasCoverImage: true },
      spotlight: { hasGroomBrideImages: false, showTitles: false },
      timeline: { enabled: true },
      gallery: { maxImages: 10 },
      story: { enabled: true },
      rsvp: { enabled: true },
      gift: { enabled: true },
    },
  },
  {
    id: 2,
    code: "minimal-green",
    name: "Minimal Green",
    style: "Tinh giản",
    preview:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&h=800&fit=crop&auto=format",
    themeClass: "theme-green",
    tier: "basic",
    price: 460000,
    accentColor: "#2d5a27",
    envelopeKey: "minimal",
    timelineKey: "simple",
    galleryKey: "grid",
    schema: {
      basicInfo: {
        hasParentsInfo: false,
        hasRankInfo: false,
        hasAddressInfo: false,
      },
      cover: { hasBackgroundVideo: false, hasCoverImage: true },
      spotlight: { hasGroomBrideImages: true, showTitles: true },
      timeline: { enabled: true },
      gallery: { maxImages: 20 },
      story: { enabled: true },
      rsvp: { enabled: true },
      gift: { enabled: true },
    },
  },
  {
    id: 3,
    code: "classic-white",
    name: "Classic White",
    style: "Cổ điển",
    preview:
      "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=600&h=800&fit=crop&auto=format",
    themeClass: "theme-modern",
    tier: "basic",
    price: 460000,
    accentColor: "#7a5c4f",
    envelopeKey: "minimal",
    timelineKey: "simple",
    galleryKey: "grid",
    schema: {
      basicInfo: {
        hasParentsInfo: true,
        hasRankInfo: true,
        hasAddressInfo: true,
      },
      cover: { hasBackgroundVideo: false, hasCoverImage: true },
      spotlight: { hasGroomBrideImages: true, showTitles: true },
      timeline: { enabled: true },
      gallery: { maxImages: 20 },
      story: { enabled: true },
      rsvp: { enabled: true },
      gift: { enabled: true },
    },
  },
];
